#!/usr/bin/env node
/**
 * 聚合插件生成器（hundun-dsh monorepo）。
 *
 * 聚合载包是一个纯 carrier 包：其 cordis.patch.yml 是各子插件 insert 行的拼接，
 * 其 package.json dependencies 以 "workspace:*" 引用全部子插件。DSH loader 从
 * profile 根解析 patch 行，所以子插件作为普通依赖安装（pnpm 默认 hoisted 布局下
 * 提升到顶层）；README 记录了 strict-layout profile 的 hoist 设置。
 *
 * 用法：
 *   node scripts/aggregate.mjs            # 重新生成并写盘
 *   node scripts/aggregate.mjs --check    # 仅校验；有漂移则退出码 1
 *
 * 每个聚合包带一份手写的 aggregate.yml 清单：
 *
 *   patchFrom:
 *     - ../dsh-workspace-canvas  # 贡献该子包 cordis.patch.yml 的 insert 行（嵌套聚合递归展开）
 *   deps:
 *     - ../dsh-workspace-canvas  # 解析为子包 package.json 的 name，写入 dependencies: workspace:*
 *   self: compat           # 可选：聚合包自身作为插件加载（宿主/浏览器半区）的补丁行
 *
 * 幂等：可随时重跑。只写它拥有的聚合包内文件，不碰其他包或 git 状态。
 */
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve as resolvePath } from 'node:path'
import { fileURLToPath } from 'node:url'

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolvePath(SCRIPT_DIR, '..')
const CHECK = process.argv.includes('--check')

const PATCH_HEADER = [
  '# AUTO-GENERATED by scripts/aggregate.mjs — do not edit',
  '# This file is derived from the aggregate.yml manifest in this package;',
  '# edit aggregate.yml and rerun `node scripts/aggregate.mjs`.',
]

/** 目录下直接子目录（非递归，排序）。 */
function listSubdirs(dir) {
  if (!existsSync(dir)) return []
  return readdirSync(dir)
    .filter((entry) => {
      try {
        return statSync(join(dir, entry)).isDirectory()
      } catch {
        return false
      }
    })
    .sort()
}

/** 找到所有带 aggregate.yml 的聚合包（packages/*）。 */
function findAggregates() {
  return listSubdirs(join(REPO_ROOT, 'packages'))
    .map((entry) => join(REPO_ROOT, 'packages', entry))
    .filter((dir) => existsSync(join(dir, 'aggregate.yml')))
    .map((pkgDir) => ({ pkgDir, ymlPath: join(pkgDir, 'aggregate.yml') }))
}

/**
 * 解析手写清单。有意的 YAML 子集：跳过注释/空行，"<key>:" 起段，"- <value>" 归段。
 */
function parseManifest(ymlPath) {
  const manifest = { patchFrom: [], deps: [], self: null }
  let section = null
  for (const raw of readFileSync(ymlPath, 'utf8').split(/\r?\n/)) {
    const line = raw.trim()
    if (!line || line.startsWith('#')) continue
    const sectionMatch = line.match(/^[A-Za-z0-9_-]+:\s*$/)
    if (sectionMatch) {
      section = line.slice(0, -1)
      continue
    }
    const entryMatch = line.match(/^-\s+(.+)$/)
    if (!entryMatch) continue
    const entry = entryMatch[1].trim().replace(/\s+#.*$/, '')
    if (section === 'patchFrom') manifest.patchFrom.push(entry)
    else if (section === 'deps') manifest.deps.push(entry)
    else if (section === 'self') {
      if (manifest.self !== null && manifest.self !== entry) {
        console.warn(`aggregate.yml 定义了多个 self（${manifest.self}, ${entry}）；保留最后一个`)
      }
      manifest.self = entry
    }
  }
  return manifest
}

/** 从子包 cordis.patch.yml 提取 {id, name} 行（固定格式："- id:" 后紧跟 "name:"）。 */
function parsePatchRows(patchPath, errors) {
  const significant = []
  for (const [i, raw] of readFileSync(patchPath, 'utf8').split(/\r?\n/).entries()) {
    const text = raw.trim()
    if (text && !text.startsWith('#')) significant.push({ text, line: i + 1 })
  }
  const rows = []
  for (let i = 0; i < significant.length; i++) {
    const idMatch = significant[i].text.match(/^-\s*id:\s*(\S+)\s*$/)
    if (!idMatch) continue
    const next = significant[i + 1]
    if (!next) {
      errors.push(`${patchPath}:${significant[i].line}: "- id:" 行后缺少 "name:" 行`)
      continue
    }
    const nameMatch = next.text.match(/^name:\s*(['"])([^'"]+)\1\s*$/)
      || next.text.match(/^name:\s*(\S+)\s*$/)
    if (!nameMatch) {
      errors.push(`${patchPath}:${next.line}: 期望 "- id: ${idMatch[1]}" 后紧跟 "name:" 行`)
      continue
    }
    rows.push({ id: idMatch[1], name: nameMatch[2] ?? nameMatch[1] })
    i++ // 消费配对的 name 行
  }
  return rows
}

/**
 * 收集一个 patchFrom 条目的补丁行。聚合包递归展开（防环）；叶子包贡献自身
 * cordis.patch.yml 的解析行。每个 block 记住叶子条目与经过的聚合链，用于注释头。
 */
function collectRows(pkgDir, entry, via, visited, errors, blocks) {
  const manifestPath = join(pkgDir, 'aggregate.yml')
  if (existsSync(manifestPath)) {
    if (visited.has(pkgDir)) {
      errors.push(`聚合环：${[...visited, pkgDir].join(' -> ')}`)
      return
    }
    visited.add(pkgDir)
    const manifest = parseManifest(manifestPath)
    for (const sub of manifest.patchFrom) {
      const subDir = resolvePath(pkgDir, sub)
      if (!existsSync(subDir)) {
        errors.push(`patchFrom 目标不存在：${manifestPath} -> ${sub}（${subDir}）`)
        continue
      }
      collectRows(subDir, sub, [...via, entry], visited, errors, blocks)
    }
    visited.delete(pkgDir)
    return
  }
  const patchPath = join(pkgDir, 'cordis.patch.yml')
  if (!existsSync(patchPath)) {
    errors.push(`patchFrom 目标没有 cordis.patch.yml：${pkgDir}（经 ${[...via, entry].join(' -> ')}）`)
    return
  }
  const rows = parsePatchRows(patchPath, errors)
  if (rows.length === 0) {
    errors.push(`从 ${patchPath} 未解析出任何插件行`)
    return
  }
  blocks.push({ entry, via, rows })
}

/** 渲染聚合 cordis.patch.yml：头 + 每源 insert 块。 */
function renderPatch(blocks) {
  const lines = [...PATCH_HEADER]
  for (const block of blocks) {
    const chain = block.via.length ? `（经 ${block.via.join(' -> ')}）` : ''
    lines.push('', `# from ${block.entry}${chain}`, '- insert:')
    for (const row of block.rows) {
      lines.push(`    - id: ${row.id}`)
      lines.push(`      name: '${row.name}'`)
    }
  }
  return lines.join('\n') + '\n'
}

/** 把清单条目解析为包名（读每个子包的 package.json）。 */
function resolveEntries(pkgDir, entries, section, errors) {
  const resolved = []
  for (const entry of entries) {
    const depDir = resolvePath(pkgDir, entry)
    const pkgPath = join(depDir, 'package.json')
    if (!existsSync(pkgPath)) {
      errors.push(`${section} 目标没有 package.json：${join(pkgDir, 'aggregate.yml')} -> ${entry}（${pkgPath}）`)
      continue
    }
    let name
    try {
      name = JSON.parse(readFileSync(pkgPath, 'utf8')).name
    } catch (e) {
      errors.push(`无法读取 ${pkgPath}：${e.message}`)
      continue
    }
    if (!name) {
      errors.push(`缺少 "name" 字段：${pkgPath}`)
      continue
    }
    resolved.push({ name, entry })
  }
  return resolved
}

/**
 * 重建聚合包 package.json：清单每个 deps 条目成为 "workspace:*" 依赖；
 * 其余字段保留。dependencies 中残留的 "workspace:*" 条目（不再在清单内）删除——
 * 聚合载包的 workspace 依赖以清单为唯一事实源（删除子插件时同步移除），
 * 非 workspace 的手写依赖（版本锁定等）保留。
 */
function renderPackageJson(pkgPath, resolvedDeps) {
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
  const next = {}
  for (const { name } of resolvedDeps) next[name] = 'workspace:*'
  for (const key of Object.keys(pkg.dependencies ?? {}).filter((k) => !(k in next)).sort()) {
    // 残留的 workspace:* 引用视为清单删除的遗留（如 dsh-hello 移除），丢弃；
    // 其余（版本锁定等手写依赖）保留。
    if (pkg.dependencies[key] === 'workspace:*') continue
    next[key] = pkg.dependencies[key]
  }
  if (Object.keys(next).length) pkg.dependencies = next
  else delete pkg.dependencies
  delete pkg.peerDependencies
  return JSON.stringify(pkg, null, 2) + '\n'
}

console.log(`[aggregate] 扫描 ${join(REPO_ROOT, 'packages')} 下的 aggregate.yml...`)
const aggregates = findAggregates()
if (aggregates.length === 0) {
  console.log('[aggregate] 未发现 aggregate.yml；无事可做。')
  process.exit(0)
}

const errors = []
const results = []
for (const { pkgDir, ymlPath } of aggregates) {
  const rel = relative(REPO_ROOT, pkgDir)
  const manifest = parseManifest(ymlPath)
  const blocks = []
  const visited = new Set()
  for (const entry of manifest.patchFrom) {
    const target = resolvePath(pkgDir, entry)
    if (!existsSync(target)) {
      errors.push(`patchFrom 目标不存在：${ymlPath} -> ${entry}（${target}）`)
      continue
    }
    collectRows(target, entry, [], visited, errors, blocks)
  }
  if (manifest.self) {
    // self：聚合包通过一行补丁加载自身的插件（宿主 + 浏览器半区）。
    // unshift 保持 self 块恒在渲染补丁最前，顺序不随 patchFrom 漂移。
    if (!/^[a-z0-9-]+$/.test(manifest.self)) {
      errors.push(`非法的 self 条目 '${manifest.self}'（须匹配 ^[a-z0-9-]+$）；跳过 self 块`)
    } else {
      let selfName
      try {
        selfName = JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf8')).name
      } catch (e) {
        errors.push(`无法读取自身包名：${e.message}`)
      }
      if (selfName) blocks.unshift({ entry: 'self', via: [], rows: [{ id: manifest.self, name: selfName }] })
    }
  }
  if (manifest.patchFrom.length === 0 && !manifest.self) {
    console.log(`[aggregate] WARN ${rel}：aggregate.yml 没有 patchFrom 条目（补丁将为空）`)
  }
  const patch = renderPatch(blocks)
  const resolvedDeps = resolveEntries(pkgDir, manifest.deps, 'deps', errors)
  const pkgJson = renderPackageJson(join(pkgDir, 'package.json'), resolvedDeps)
  results.push({ rel, blocks, patch, resolvedDeps, pkgJson })
}

let failed = false
if (errors.length) {
  for (const e of errors) console.error(`[aggregate] ERROR ${e}`)
  failed = true
}
if (failed) {
  console.error(CHECK ? '[aggregate] check FAILED：磁盘内容与生成内容不符' : '[aggregate] FAILED：见上方错误；未写任何文件')
  process.exit(1)
}

for (const r of results) {
  const patchPath = join(REPO_ROOT, r.rel, 'cordis.patch.yml')
  const pkgPath = join(REPO_ROOT, r.rel, 'package.json')
  if (CHECK) {
    const diffs = []
    if (!existsSync(patchPath) || readFileSync(patchPath, 'utf8') !== r.patch) diffs.push(relative(REPO_ROOT, patchPath))
    if (!existsSync(pkgPath) || readFileSync(pkgPath, 'utf8') !== r.pkgJson) diffs.push(relative(REPO_ROOT, pkgPath))
    if (diffs.length) {
      for (const d of diffs) console.log(`[aggregate] check：${d} 与生成内容不符`)
      failed = true
    } else {
      const rows = r.blocks.reduce((n, b) => n + b.rows.length, 0)
      console.log(`[aggregate] check OK：${r.rel}（${rows} 行，${r.resolvedDeps.length} 依赖）`)
    }
  } else {
    writeFileSync(patchPath, r.patch)
    console.log(`[aggregate] 已写 ${relative(REPO_ROOT, patchPath)}（${r.blocks.length} 个源块，${r.blocks.reduce((n, b) => n + b.rows.length, 0)} 行）`)
    writeFileSync(pkgPath, r.pkgJson)
    console.log(`[aggregate] 已写 ${relative(REPO_ROOT, pkgPath)}（${r.resolvedDeps.length} 个 workspace 依赖）`)
  }
}

if (failed) {
  console.error('[aggregate] check FAILED：磁盘内容与生成内容不符')
  process.exit(1)
}
console.log('[aggregate] done')
